Fix build of PRoot on old distros, like Centos 5.
There was two issues:

    In file included from ./execve/shebang.c:25:
    /usr/include/sys/types.h:46: error: conflicting types for ‘loff_t’
    /usr/include/linux/types.h:30: error: previous declaration of ‘loff_t’ was here

and:

    ./ptrace/wait.c: In function ‘update_wait_status’:
    ./ptrace/wait.c:137: error: assignment of read-only member ‘__in’
    ./ptrace/wait.c:138: error: assignment of read-only member ‘__in’

These two issues are likely due to old bugs in GNU libc headers.