care: Attach the archive destructor once it is fully created.
This avoids a lot of pointless messages emitted by the finalization
code.  Before ("test" does not exist):

    care error: can't open archive '/test/foo.tar': Failed to open '/test/foo.tar'
     warning: can't archive 're-execute.sh'
     warning: can't archive 'README.txt'
     warning: can't archive 'proot'
     info: ----------------------------------------------------------------------
     info: If the execution didn't go as expected: search for "conceal" in `care -h`.
     info: CARE output: /test/foo.tar
    care warning: can't initialize the care extension
    fatal error: see `care --help` or `man care`.

Now:

    care error: can't open archive '/test/foo.tar': Failed to open '/test/foo.tar'
    care warning: can't initialize the care extension
    fatal error: see `care --help` or `man care`.