Add a couple of recommended bindings.
* "/run/shm" is used for shared semaphores on Ubuntu.  If it is not
  mounted, some programs may not work:

    $ bitbake

    File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
      sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
    OSError: [Errno 38] Function not implemented

* "/run" as whole can be safely bound for regular users.  When faking
  privileges, package managers might attempt to write (without
  success) in "/run/var".

* "/var/run/dbus/system_bus_socket" is a volatile path for CARE, so it
  might be useful to PRoot user too.